server: 
  port: 8081
  servlet:
    context-path: /jpa
  tomcat:
    uri-encoding: UTF-8
    threads:      max: 100      min-spare: 30

spring:
  application:
    name: ssh
    
  devtools:
    restart:
      enabled: true  #设置开启热部署
      
  datasource:
    url: jdbc:mysql://localhost:3306/jpa-demo?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=GMT%2B8
    username: root
    password: 
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 2
      max-active: 5
      min-idle: 1
      max-wait: 60000 
      time-between-eviction-runs-millis: 60000 
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      max-open-prepared-statements: 20
      remove-abandoned: true    
      log-abandoned: true
      
  servlet:
     multipart:
       max-file-size: 100MB
       max-request-size: 100MB
       # 配置springDataJPA相关内容  jpa:    database: mysql
    show-sql: true
           # 可以直接根据entity创建表
    hibernate:      ddl-auto: update

pagehelper:
  helper-dialect: mysql
  row-bounds-with-count: true
  pageSizeZero: true
  reasonable: true
  support-methods-arguments: true
  params: count=countSql


